# This is a waka readme stats update workflow that is triggered on push

name: waka

on: push

jobs:
  update-readme:
    name: Update the WakaTime Stat
    runs-on: ubuntu-latest

    steps:
    - name: waka
      # You may pin to the exact commit or the version.
      # uses: matchai/waka-box@4cbedd0fe38af5c3a475a38240866563896034a2
      uses: matchai/waka-box@v4.0.5
      with:
          # WakaTime API key stored in secrets, do not directly paste it here
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          # Automatic github token
          GITHUB_TOKEN: ${{ github.token }}
          # Branch - newer GitHub repositories have "main" as default branch, change to main in that case, default is master
          BRANCH: "main"
          # Manual Commit messages - write your own messages here
          COMMIT_MSG: "Automated Coding Activity Update :alien:"
